# Generated by Django 5.1 on 2026-04-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteHH',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('total_hh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_practicas', models.IntegerField(default=0)),
                ('total_asistentes', models.IntegerField(default=0)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
            ],
        ),
    ]
