# Generated by Django 5.1 on 2026-04-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('numero_colaborador', models.CharField(max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='PracticaOperativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_minutos', models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (60, '60 Minutos')])),
                ('estatus', models.CharField(choices=[('Programado', 'Programado'), ('Pendiente', 'Pendiente'), ('Completado', 'Completado')], default='Programado', max_length=50)),
                ('fecha_expiracion', models.DateField()),
                ('objetivo', models.TextField(blank=True)),
                ('descripcion_estandar', models.TextField(blank=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructores.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaPractica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firma', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.colaborador')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.practicaoperativa')),
            ],
        ),
    ]
