# Generated by Django 5.1 on 2026-05-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaoperativa',
            name='duracion_minutos',
            field=models.IntegerField(choices=[(5, '5 Minutos'), (10, '10 Minutos'), (15, '15 Minutos'), (20, '20 Minutos')]),
        ),
    ]
