# Generated by Django 5.1 on 2026-05-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0002_alter_practicaoperativa_duracion_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaoperativa',
            name='duracion_minutos',
            field=models.IntegerField(choices=[(10, '10 Minutos'), (15, '15 Minutos'), (20, '20 Minutos'), (25, '25 Minutos'), (30, '30 Minutos'), (35, '35 Minutos'), (40, '40 Minutos'), (45, '45 Minutos'), (50, '50 Minutos'), (55, '55 Minutos'), (60, '60 Minutos')]),
        ),
    ]
