# Generated by Django 5.1 on 2026-04-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('enfoque', models.CharField(choices=[('Generales', 'Generales'), ('Cristal', 'Cristal'), ('Operación', 'Operación'), ('Institucionales', 'Institucionales'), ('Seguridad', 'Seguridad'), ('Servicio', 'Servicio')], max_length=50)),
            ],
        ),
    ]
